<?php

function ideal_panes_ctools_plugin_directory($module, $plugin) {
  if ($module == 'page_manager' || $module == 'panels' || $module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}


function ideal_panes_theme_registry_alter(&$theme_registry) {
    if (!empty($theme_registry['menu_link'])) {
      $theme_registry['menu_link']['function'] = 'menu_icon_menu_link';
    }
}


function menu_icon_menu_link($variables) {
  $element = $variables['element'];
  global $user;
  $sub_menu = '';
  if ($element['#below']) {
    $sub_menu = drupal_render($element['#below']);
  }
  $output = l($element['#title'], $element['#href'], $element['#localized_options']);
  if (isset($element['#localized_options']['menu_icon'])) {
    if ($element['#localized_options']['menu_icon']['enable'] == 1) {
      $element['#attributes']['title'] = $element['#title'];
      $output = l('', $element['#href'], $element['#localized_options']);
    }
  }
  $link = '<li' . drupal_attributes($element['#attributes']) . '>' . $output . $sub_menu . "</li>\n";
  if ($element['#title'] == t('My account') ) {
         $image = theme('user_picture', array('account' => $user));
       $link =  $image . '<li' . drupal_attributes($element['#attributes']) . '>'. $output . $sub_menu . "</li>\n";
  }
  return $link;
}

/**
 * Implements hook_form_alter().
 */
function ideal_panes_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'ctools_block_content_type_edit_form' ||
    $form_id == 'ctools_custom_content_type_edit_form') {
    $form['title_class'] = [
      '#default_value' => !empty($form_state['conf']['title_class']) ? $form_state['conf']['title_class'] : '',
      '#type' => 'textfield',
      '#title' => 'Title Class',
      '#id' => 'title-class-textfield',
    ];

    $form['#submit'][] = 'ideal_panes_additional_settings_submit';

    if ($form_id == 'ctools_custom_content_type_edit_form') {
      $form['body']['#weight'] = 99;
      $form['title_class']['#weight'] = 98;
    }
  }
}

function ideal_panes_additional_settings_submit(&$form, &$form_state) {
  if (isset($form_state['values']['title_class'])) {
    $form_state['conf']['title_class'] = $form_state['values']['title_class'];
  }
}
