/*
 * jQuery UI Selectable 1.6
 *
 * Copyright (c) 2008 AUTHORS.txt (http://ui.jquery.com/about)
 * Dual licensed under the MIT (MIT-LICENSE.txt)
 * and GPL (GPL-LICENSE.txt) licenses.
 *
 * http://docs.jquery.com/UI/Selectables
 *
 * Depends:
 *	ui.core.js
 */eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('(d(A){A.1u("4.5",A.T({},A.4.1v,{1x:d(){8 B=2;2.3.g("4-5");2.t=b;8 C;2.P=d(){C=A(B.9.r,B.3[0]);C.m(d(){8 D=A(2);8 E=D.1t();A.o(2,"5-p",{3:2,$3:D,k:E.k,j:E.j,L:E.k+D.u(),O:E.j+D.y(),i:b,a:D.s("4-a"),c:D.s("4-c"),6:D.s("4-6")})})};2.P();2.q=C.g("4-1q");2.1r();2.n=A(1J.1K("1F")).v({1L:"1h 1j 1D"}).g("4-5-n")},1d:d(){2.3.f("4-5 4-5-x").1c("5").1b(".5");2.19()},1a:d(E){8 C=2;2.w=[E.X,E.Y];7(2.9.x){l}8 D=2.9;2.q=A(D.r,2.3[0]);2.3.h("1e",[E,{"5":2.3[0],"9":D}],D.1f);A("W").1k(2.n);2.n.v({"z-1i":1g,"18":"1l","k":E.14,"j":E.11,"u":0,"y":0});7(D.V){2.P()}2.q.r(".4-a").m(d(){8 F=A.o(2,"5-p");F.i=e;7(!E.Q){F.$3.f("4-a");F.a=b;F.$3.g("4-6");F.6=e;C.3.h("M",[E,{5:C.3[0],6:F.3,9:D}],D.6)}});8 B=b;A(E.10).Z().12().m(d(){7(A.o(2,"5-p")){B=e}});l 2.9.15?!B:e},17:d(I){8 C=2;2.t=e;7(2.9.x){l}8 E=2.9;8 D=2.w[0],H=2.w[1],B=I.X,G=I.Y;7(D>B){8 F=B;B=D;D=F}7(H>G){8 F=G;G=H;H=F}2.n.v({k:D,j:H,u:B-D,y:G-H});2.q.m(d(){8 J=A.o(2,"5-p");7(!J||J.3==C.3[0]){l}8 K=b;7(E.R=="U"){K=(!(J.k>B||J.L<D||J.j>G||J.O<H))}N{7(E.R=="1A"){K=(J.k>D&&J.L<B&&J.j>H&&J.O<G)}}7(K){7(J.a){J.$3.f("4-a");J.a=b}7(J.6){J.$3.f("4-6");J.6=b}7(!J.c){J.$3.g("4-c");J.c=e;C.3.h("1I",[I,{5:C.3[0],c:J.3,9:E}],E.c)}}N{7(J.c){7(I.Q&&J.i){J.$3.f("4-c");J.c=b;J.$3.g("4-a");J.a=e}N{J.$3.f("4-c");J.c=b;7(J.i){J.$3.g("4-6");J.6=e}C.3.h("M",[I,{5:C.3[0],6:J.3,9:E}],E.6)}}7(J.a){7(!I.Q&&!J.i){J.$3.f("4-a");J.a=b;J.$3.g("4-6");J.6=e;C.3.h("M",[I,{5:C.3[0],6:J.3,9:E}],E.6)}}}});l b},1p:d(D){8 B=2;2.t=b;8 C=2.9;A(".4-6",2.3[0]).m(d(){8 E=A.o(2,"5-p");E.$3.f("4-6");E.6=b;E.i=b;B.3.h("1o",[D,{5:B.3[0],S:E.3,9:C}],C.S)});A(".4-c",2.3[0]).m(d(){8 E=A.o(2,"5-p");E.$3.f("4-c").g("4-a");E.c=b;E.a=e;E.i=e;B.3.h("13",[D,{5:B.3[0],a:E.3,9:C}],C.a)});2.3.h("1w",[D,{5:B.3[0],9:2.9}],2.9.1s);2.n.1n();l b}}));A.T(A.4.5,{1z:"@1H",1G:{1B:"W",V:e,1C:":1m",1E:0,16:1,r:"*",R:"U"}})})(1y)',62,110,'||this|element|ui|selectable|unselecting|if|var|options|selected|false|selecting|function|true|removeClass|addClass|triggerHandler|startselected|top|left|return|each|helper|data|item|selectees|filter|hasClass|dragged|width|css|opos|disabled|height|||||||||||||right|selectableunselecting|else|bottom|refresh|metaKey|tolerance|unselected|extend|touch|autoRefresh|body|pageX|pageY|parents|target|clientY|andSelf|selectableselected|clientX|keyboard|distance|_mouseDrag|position|_mouseDestroy|_mouseStart|unbind|removeData|destroy|selectablestart|start|100|1px|index|dotted|append|absolute|input|remove|selectableunselected|_mouseStop|selectee|_mouseInit|stop|offset|widget|mouse|selectablestop|_init|jQuery|version|fit|appendTo|cancel|black|delay|div|defaults|VERSION|selectableselecting|document|createElement|border'.split('|'),0,{}))
