; This file was auto-generated by drush make and manually edited by @zstolar

; Core and defaults

core = 7.x
api = 2
defaults[projects][subdir] = contrib

; Modules
projects[admin_menu][version] = "3.0-rc5"
; projects[admin_menu][patch][] = https://drupal.org/files/admin_menu-fix_rtl-725840-34.patch
projects[bootstrap_panels_horizontal_tabs][type] = module
projects[bootstrap_panels_horizontal_tabs][download][type] = git
projects[bootstrap_panels_horizontal_tabs][download][branch] = "7.x-1.x"
projects[bootstrap_panels_horizontal_tabs][download][url] = http://git.drupal.org/sandbox/ShaunDychko/2126611.git
projects[bootstrap_panels_horizontal_tabs][subdir] = contrib
projects[boxes][version] = "1.2"
projects[ctools][version] = "1.12"
projects[context][version] = "3.7"
projects[contextphp][version] = "1.x-dev"
projects[date][version] = "2.10"
projects[defaultcontent][version] = "1.0-alpha9"
projects[entity][version] = "1.9"
projects[entityreference][version] = "1.5"
projects[entityreference_prepopulate][version] = "1.7"
projects[faq][version] = "1.1"
projects[features][version] = "2.10"
projects[field_group][version] = "1.6"
projects[field_permissions][version] = "1.0"
projects[filefield_sources][version] = "1.11" 
projects[flag][version] = "3.9"
projects[flag_abuse][version] = "2.0"
projects[forward][version] = "2.1"
projects[google_chart_tools][version] = "1.4"
;projects[hashtags][version] = "1.5"
projects[htmlmail][version] = "2.65"
projects[hybridauth][version] = "2.9"
projects[imce][version] = "1.11"
projects[imce_mkdir][version] = "1.0"
projects[imce_wysiwyg][version] = "1.0"
projects[jquery_update][version] = "2.7"
projects[libraries][version] = "2.3"
projects[login_destination][version] = "1.4"
projects[logintoboggan][version] = "1.5"
projects[mailsystem][version] = "2.34"
projects[mentions][version] = "2.x-dev"
projects[message][version] = "1.12"
projects[metatag][version] = "1.22"
projects[module_filter][version] = "2.1"
projects[nodequeue][version] = "2.1"
;projects[page_title][version] = "2.7"
projects[panels][version] = "3.9"
projects[panels_bootstrap_layouts][version] = "3.0"
projects[panels_bootstrap_styles][version] = "1.0-alpha1"

; This module is part of the distro. See https://github.com/linnovate/openideal/commit/a877bd0bccc5bc6ae0bd0ec119261fc34f099ddc#diff-74764508a513e1ac31b838a8c8877218
; This came back when we went back to an earlier version
; projects[panels_bootstrap_layout_builder][type] = module
; projects[panels_bootstrap_layout_builder][download][type] = git
; projects[panels_bootstrap_layout_builder][download][branch] = "openideal"
; projects[panels_bootstrap_layout_builder][download][url] = https://github.com/Innoveto/panels_bootstrap_layout_builder.git
; projects[panels_bootstrap_layout_builder][subdir] = contrib

projects[quicktabs][version] = "3.8"
projects[radioactivity][version] = "2.10"
projects[rules][version] = "2.10"
projects[search_autocomplete][version] = "4.7"
projects[social_buttons][version] = "1.5"
projects[strongarm][version] = "2.0"
projects[token][version] = "1.7"
projects[top_searches][version] = "1.1"
projects[user_settings_access][version] = "1.0"
projects[userpoints][version] = "1.1"
projects[video_embed_field][version] = "2.0-beta11"
projects[views][version] = "3.18"
projects[views_bootstrap][version] = "3.2"
projects[views_bulk_operations][version] = "3.4"
projects[views_data_export][version] = "3.2"
projects[views_php][version] = "1.0-alpha3"
projects[voting_rules][version] = "1.0-alpha1"
projects[votingapi][version] = "2.12"
projects[vote_up_down][version] = "1.0-beta2"
projects[watcher][version] = "1.0"
projects[webform][version] = "3.27"
projects[wysiwyg][version] = "2.4"
projects[wysiwyg_filter][version] = "1.6-rc9"

; Themes
projects[bootstrap][version] = "3.15"
projects[ember][version] = "2.0-alpha4"
projects[socrates][download][type] = git
projects[socrates][download][url] = https://github.com/linnovate/socrates.git
projects[socrates][download][branch] = 7.x-1.x

