; This file was auto-generated by drush make
core = 7.x
api = 2
defaults[projects][subdir] = contrib

; Modules

projects[views_bulk_operations][version] = "3.1"
projects[views_bulk_operations][subdir] = contrib

projects[addressfield][version] = "1.0-beta4"
projects[addressfield][subdir] = contrib

projects[admin_menu][version] = "3.0-rc4"
projects[admin_menu][subdir] = contrib
projects[admin_menu][patch][] = https://drupal.org/files/admin_menu-fix_rtl-725840-34.patch

projects[google_chart_tools][version] = "1.4"
projects[google_chart_tools][subdir] = contrib

projects[boxes][version] = "1.1"
projects[boxes][subdir] = contrib

projects[ctools][version] = "1.3"
projects[ctools][subdir] = contrib

projects[context][version] = "3.0-beta7"
projects[context][subdir] = contrib

projects[contextphp][version] = "1.x-dev"
projects[contextphp][subdir] = contrib

projects[date][version] = "2.6"
projects[date][subdir] = contrib

projects[defaultcontent][version] = "1.0-alpha9"
projects[defaultcontent][subdir] = contrib

projects[entity][version] = "1.2"
projects[entity][subdir] = contrib

projects[entityreference][version] = "1.0"
projects[entityreference][subdir] = contrib

projects[faq][version] = "1.0-rc2"
projects[faq][subdir] = contrib

projects[features][version] = "1.0"
projects[features][subdir] = contrib

projects[field_group][version] = "1.2"
projects[field_group][subdir] = contrib

projects[field_permissions][version] = "1.0-beta2"
projects[field_permissions][subdir] = contrib

projects[filefield_sources][version] = "1.8"
projects[filefield_sources][subdir] = contrib

projects[flag][version] = "2.1"
projects[flag][subdir] = contrib

projects[flag_abuse][version] = "2.0-alpha1"
projects[flag_abuse][subdir] = contrib

projects[forward][version] = "1.4"
projects[forward][subdir] = contrib

projects[htmlmail][version] = "2.65"
projects[htmlmail][subdir] = contrib

projects[ideal_comments][version] = "1.1"
projects[ideal_comments][subdir] = contrib

projects[imce][version] = "1.7"
projects[imce][subdir] = contrib

projects[imce_mkdir][version] = "1.0"
projects[imce_mkdir][subdir] = contrib

projects[imce_wysiwyg][version] = "1.0"
projects[imce_wysiwyg][subdir] = contrib

projects[libraries][version] = "2.1"
projects[libraries][subdir] = contrib

projects[login_destination][version] = "1.1"
projects[login_destination][subdir] = contrib

projects[logintoboggan][version] = "1.3"
projects[logintoboggan][subdir] = contrib

projects[mailsystem][version] = "2.34"
projects[mailsystem][subdir] = contrib

projects[message][version] = "1.9"
projects[message][subdir] = contrib

projects[metatag][version] = "1.0-beta7"
projects[metatag][subdir] = contrib

projects[module_filter][version] = "1.8"
projects[module_filter][subdir] = contrib

projects[nodequeue][version] = "2.0-beta1"
projects[nodequeue][subdir] = contrib

projects[page_title][version] = "2.7"
projects[page_title][subdir] = contrib

projects[quicktabs][version] = "3.5"
projects[quicktabs][subdir] = contrib

projects[radioactivity][version] = "2.8"
projects[radioactivity][subdir] = contrib

projects[rules][version] = "2.3"
projects[rules][subdir] = contrib

projects[search_autocomplete][version] = "3.2"
projects[search_autocomplete][subdir] = contrib

projects[social_buttons][version] = "1.3"
projects[social_buttons][subdir] = contrib

projects[strongarm][version] = "2.0"
projects[strongarm][subdir] = contrib

projects[token][version] = "1.5"
projects[token][subdir] = contrib

projects[top_searches][version] = "1.0"
projects[top_searches][subdir] = contrib

projects[userpoints][version] = "1.0"
projects[userpoints][subdir] = contrib

projects[video_embed_field][version] = "2.0-beta5"
projects[video_embed_field][subdir] = contrib

projects[views][version] = "3.7"
projects[views][subdir] = contrib

projects[views_data_export][version] = "3.0-beta6"
projects[views_data_export][subdir] = contrib

projects[views_php][version] = "1.x-dev"
projects[views_php][subdir] = contrib

projects[voting_rules][version] = "1.0-alpha1"
projects[voting_rules][subdir] = contrib

projects[votingapi][version] = "2.11"
projects[votingapi][subdir] = contrib

projects[vote_up_down][version] = "1.0-alpha1"
projects[vote_up_down][subdir] = contrib

projects[watcher][version] = "1.x-dev"
projects[watcher][subdir] = contrib

projects[webform][version] = "3.19"
projects[webform][subdir] = contrib

projects[wysiwyg][version] = "2.2"
projects[wysiwyg][subdir] = contrib

projects[wysiwyg_filter][version] = "1.6-rc2"
projects[wysiwyg_filter][subdir] = contrib

; Themes
projects[bootstrap][version] = "3.0"
projects[bootstrap][subdir] = ""

projects[socrates][version] = "1.x"
projects[socrates][subdir] = ""
