; This file was auto-generated by drush make
core = 7.x

api = 2

; Modules

projects[views_bulk_operations][version] = "3.1"

projects[addressfield][version] = "1.0-beta4"

projects[admin_menu][version] = "3.0-rc4"

projects[google_chart_tools][version] = "1.4"

projects[boxes][version] = "1.1"

projects[ctools][version] = "1.3"

projects[context][version] = "3.0-beta7"

projects[contextphp][version] = "1.x-dev"

projects[date][version] = "2.6"

projects[defaultcontent][version] = "1.0-alpha9"

projects[entity][version] = "1.2"

projects[entityreference][version] = "1.0"

projects[faq][version] = "1.0-rc2"

projects[features][version] = "1.0"

projects[field_group][version] = "1.2"

projects[field_permissions][version] = "1.0-beta2"

projects[filefield_sources][version] = "1.8"

projects[flag][version] = "2.1"

projects[flag_abuse][version] = "2.0-alpha1"

projects[forward][version] = "1.4"

projects[htmlmail][version] = "2.65"

projects[ideal_comments][version] = "1.1"

projects[imce][version] = "1.7"

projects[imce_mkdir][version] = "1.0"

projects[imce_wysiwyg][version] = "1.0"

projects[libraries][version] = "2.1"

projects[login_destination][version] = "1.1"

projects[logintoboggan][version] = "1.3"

projects[mailsystem][version] = "2.34"

projects[message][version] = "1.9"

projects[metatag][version] = "1.0-beta7"

projects[module_filter][version] = "1.8"

projects[nodequeue][version] = "2.0-beta1"

projects[page_title][version] = "2.7"

projects[quicktabs][version] = "3.5"

projects[radioactivity][version] = "2.8"

projects[rules][version] = "2.3"

projects[search_autocomplete][version] = "3.2"

projects[social_buttons][version] = "1.3"

projects[strongarm][version] = "2.0"

projects[token][version] = "1.5"

projects[top_searches][version] = "1.0"

projects[userpoints][version] = "1.0"

projects[video_embed_field][version] = "2.0-beta5"

projects[views][version] = "3.7"

projects[views_data_export][version] = "3.0-beta6"

projects[views_php][version] = "1.x-dev"

projects[voting_rules][version] = "1.0-alpha1"

projects[votingapi][version] = "2.11"

projects[vote_up_down][version] = "1.0-alpha1"

projects[watcher][version] = "1.x-dev"

projects[webform][version] = "3.19"

projects[wysiwyg][version] = "2.2"

projects[wysiwyg_filter][version] = "1.6-rc2"

; Themes
projects[sasson][version] = "2.10"

projects[plato][version] = "1.0"

