<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function metatag_test_ctools_plugin_api($owner, $api) {
  if ($owner == 'metatag' && $api == 'metatag') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_entity_info_alter().
 */
function metatag_test_entity_info_alter(&$info) {
  if (variable_get('metatag_test_entity_info_disable')) {
    $info['node']['bundles']['page']['metatags'] = FALSE;
    $info['user']['metatags'] = FALSE;
  }
}
