<?php

/**
 * @file
 * Provide the integration with Share module.
 */

/**
 * Implements hook_share_info().
 */
function service_links_share_share_info() {
  return array(
    'tab' => array(
      'module' => 'service_links_share',
      'title' => t('Service Links'),
      'enabled' => TRUE,
      'weight' => 0,
    )
  );
}

/**
 * Implements hook_share_tab().
 */
function service_links_share_share_tab($op, $args, $node = NULL) {
  switch ($op) {
    case 'process':
      if (is_object($node)) {
        if (isset($node->service_links_rendered)) {
          return $node->service_links_rendered;
        }
      }
  }
}