<?php

/**
 * @file
 * German services that extend Service Links module
 * Collected by Sanduhrs and funana
 */

/**
 * Implements hook_service_links().
 */
function german_services_service_links() {
  $links = array();

  $links['_de_alltagz'] = array(
    'name' => 'Alltagz',
    'description' => t('Add to Alltagz.'),
    'link' => 'http://www.alltagz.de/bookmarks/?action=add&popup=1&address=<encoded-url>&title=<encoded-title>&description=<resume>',
  );
  $links['_de_misterwong'] = array(
    'name' => 'Mister Wong',
    'description' => t('Bookmark this post on Mister Wong.'),
    'link' => 'http://www.mister-wong.de/index.php?action=addurl&bm_url=<encoded-url>&bm_description=<encoded-title>',
    'icon' => 'misterwong.png',
  );
  $links['_de_seoigg'] = array(
    'name' => 'SeoIGG',
    'description' => t('Bookmark this post on SeoIGG.'),
    'link' => 'http://www.seoigg.de/node/add/storylink?edit[url]=<encoded-url>&edit[title]=<encoded-title>',
  );
  $links['_de_colivia'] = array(
    'name' => 'Colivia',
    'description' => t('Bookmark this post on Colivia.'),
    'link' => 'http://www.colivia.de/submit.php?url=<encoded-url>',
  );
  $links['_de_icio'] = array(
    'name' => 'Icio',
    'description' => t('Bookmark this post on Icio.'),
    'link' => 'http://www.icio.de/add.php?url=<encoded-url>',
  );
  $links['_de_infopirat'] = array(
    'name' => 'Infopirat',
    'description' => t('Add to Infopirat.'),
    'link' => 'http://infopirat.com/node/add/userlink?edit[url]=<encoded-url>&edit[title]=<encoded-title>',
  );
  $links['_de_seekxl'] = array(
    'name' => 'seekXL',
    'description' => t('Bookmark this post on seekXL.'),
    'link' => 'http://social-bookmarking.seekxl.de/?add_url=<encoded-url>&title=<encoded-title>',
  );
  $links['_de_linkarena'] = array(
    'name' => 'Linkarena',
    'description' => t('Add to Linkarena.'),
    'link' => 'http://linkarena.com/bookmarks/addlink/?url=<encoded-url>&title=<encoded-title>',
  );
  $links['_de_netselektor'] = array(
    'name' => 'Netselektor',
    'description' => t('Bookmark this post on Netselektor.'),
    'link' => 'http://netselektor.de/speichern/neu?title=<encoded-title>&url=<encoded-url>',
  );
  $links['_de_weblinkr'] = array(
    'name' => 'Weblinkr',
    'description' => t('Bookmark this post on Weblinkr.'),
    'link' => 'http://weblinkr.com/weblinks/?action=add&address=<encoded-url>&title=<encoded-title>',
  );
  $links['_de_webnews'] = array(
    'name' => 'Webnews',
    'description' => t('Bookmark this post on Webnews.'),
    'link' => 'http://www.webnews.de/einstellen?url=<encoded-url>&title=<encoded-title>',
  );
  $links['_de_readster'] = array(
    'name' => 'Readster',
    'description' => t('Bookmark this post on Readster.'),
    'link' => 'http://www.readster.de/submit/?url=<encoded-url>&title=<encoded-title>',
  );
  $links['_de_oneview'] = array(
    'name' => 'Oneview',
    'description' => t('Bookmark this post on Oneview.'),
    'link' => 'http://www.oneview.de/quickadd/neu/addBookmark.jsf?URL=<encoded-url>&title=<encoded-title>',
  );
  $links['_de_yigg'] = array(
    'name' => 'Yigg',
    'description' => t('Add to Yigg.de.'),
    'link' => 'http://yigg.de/neu?exturl=<encoded-url>&title=<encoded-title>',
  );
  $links['_de_meinvz'] = array(
    'name' => 'MeinVZ',
    'description' => t('Share on MeinVZ, StudiVZ or SchuelerVZ.'),
    'link' => 'http://www.studivz.net/Link/Selection/Url/?u=<encoded-url>&desc=<encoded-title>',
  );
  $links['_de_xing'] = array(
    'name' => 'Xing',
    'description' => t('Share on Xing.'),
    'link' => 'https://www.xing.com/app/user?op=share&url=<raw-encoded-url>',
  );

  return $links;
}
