; This file was auto-generated by drush_make
core = 6.x

api = 2

;core
projects[acquia][type] = "core"
projects[acquia][download][type] = "get"
projects[acquia][download][url] = "http://network.acquia.com/files/downloads/acquia-drupal-1.2.34.5460.tar.gz" 

;contrib
projects[views_bulk_operations][version] = "1.10"
projects[admin][version] = "2.0"
projects[admin_menu][version] = "1.6"
projects[adminrole][version] = "1.3"
projects[advanced_help][version] = "1.2"
projects[backup_migrate][version] = "2.3"
projects[backup_migrate_files][version] = "1.x-dev"
projects[service_links][version] = "2.0"
projects[boxes][version] = "1.0"
projects[ctools][version] = "1.8"
projects[calendar][version] = "2.2"
projects[content_profile][version] = "1.0"
projects[context][version] = "3.0"
projects[contextphp][version] = "1.0-beta2"
projects[data][version] = "1.0-alpha14"
projects[date][version] = "2.4"
projects[devel][version] = "1.22"
projects[diff][version] = "2.1"
projects[email_confirm][version] = "1.4"
projects[faq][version] = "1.12"
projects[fb][version] = "3.0-beta3"
projects[features][version] = "1.0"
projects[flag][version] = "2.0-beta3"
projects[flag_abuse][version] = "2.0-rc1"
projects[heartbeat][version] = "4.10"
projects[htmlmail][version] = "1.x-dev"
projects[install_profile_api][version] = "2.1"
projects[logintoboggan][version] = "1.7"
projects[nodequeue][version] = "2.9"
projects[nodewords][version] = "1.12-beta9"
projects[nodewords_nodetype][version] = "1.7"
projects[nodewords_pagetitle][version] = "1.1"
projects[page_title][version] = "2.3"
projects[quicktabs][subdir] = ""
projects[quicktabs][version] = "3.x-dev"
projects[rules][version] = "1.3"
projects[schema][version] = "1.7"
projects[simpletest][version] = "2.10"
projects[strongarm][version] = "2.0"
projects[userpoints][version] = "1.1"
projects[voting_rules][version] = "1.0-alpha1"
projects[vote_up_down][version] = "2.1"
projects[wysiwyg][version] = "2.1"
projects[xmlsitemap][version] = "2.0-beta1"

;preeflow
projects[cookie_cache_bypass][type] = "module"

;features
projects[fe_challenge][type] = "module"
projects[fe_main][type] = "module"
projects[fe_news][type] = "module"
projects[fe_project][type] = "module"

;helper
projects[features_download][download][type] = "git"
projects[features_download][download][url] = "https://github.com/perelman/feature_download.git"
projects[features_download][type] = "module"

;custom
projects[ideal][type] = "module"
projects[ideal_challenge][type] = "module"
projects[ideal_popular][type] = "module"
projects[ideal_project][type] = "module"
projects[path_alias_cache][type] = "module"

;themes
projects[tao][version] = "3.1"
projects[tao][type] = "theme"
projects[rubik][version] = "3.0-beta1"
projects[rubik][type] = "theme"
projects[ninesixty][version] = "1.0
projects[ninesixty][type] = "theme"
;custom subtheme
projects[ideal_theme][type] = "theme"