<?php

/**
 * Implements hook_block_info().
 */
function ideal_main_block_info() {
  $blocks = array();
  $blocks['category_list'] = array(
    'info' => t('Ideal: Category list for sidebar'),
  );
  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function ideal_main_block_view($delta) {
  if (TRUE) {
    switch ($delta) {
      case 'category_list':
        $block = array(
          'subject' => '',
          'content' => theme('ideal_category_list_block'),
        );
        break;
    }
    return $block;
  }
}

/**
 * Implements hook_theme()
 */
function ideal_main_theme($existing, $type, $theme, $path) {
  return array(
    // theme function for sidebar category list
    'ideal_category_list_block' => array(
      'file' => 'ideal_main.theme.inc',
    ),
  );
}

/**
 * Count idea nodes for a given taxonomy term 
 */
function ideal_count_term_ideas($tid) {
  $query = db_select('taxonomy_index', 'ti');
  $query->condition('ti.tid', $tid, '=')
        ->fields('ti', array('nid'));
  
  $num_rows = $query->countQuery()->execute()->fetchField();
  return $num_rows;
}