<?php

/**
 * Implements hook_menu().
 */
function ideal_main_menu() {
  $items = array();
  $items['admin/config/user-interface/openideal'] = array(
    'title' => 'General Configurations',
    'access arguments' => array('access content'),
    'page callback' => 'ideal_main_config_page',
    'page arguments' => array('ideal_main_config_form'),
    'file' => 'ideal_main.admin.inc',  
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['admin/config/user-interface/openideal/general'] = array(
    'title' => 'General Configurations',
    'description' => 'General Configurations', 
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function ideal_main_block_info() {
  $blocks = array();
  $blocks['category_list'] = array(
    'info' => t('Ideal: Category list for sidebar'),
  );
  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function ideal_main_block_view($delta) {
  if (TRUE) {
    switch ($delta) {
      case 'category_list':
        $block = array(
          'subject' => '',
          'content' => theme('ideal_category_list_block'),
        );
        break;
    }
    return $block;
  }
}

/**
 * Implements hook_theme()
 */
function ideal_main_theme($existing, $type, $theme, $path) {
  return array(
    // theme function for sidebar category list
    'ideal_category_list_block' => array(
      'file' => 'ideal_main.theme.inc',
    ),
  );
}

/**
 * Count idea nodes for a given taxonomy term 
 */
function ideal_count_term_ideas($tid) {
  $query = db_select('taxonomy_index', 'ti');
  $query->condition('ti.tid', $tid, '=')
        ->fields('ti', array('nid'));
  
  $num_rows = $query->countQuery()->execute()->fetchField();
  return $num_rows;
}


/**
 *  hook_data_alter
 */
function ideal_main_views_data_alter(&$data) {
  $data['node']['uid_voted'] = array(
    'title' => t('User voted'),
    'help' => t('Display nodes only if a user voted on the node.'),
    'argument' => array(
      'field' => 'uid',
      'name table' => 'users',
      'name field' => 'name',
      'handler' => 'views_handler_argument_vote_only_user_uid',
    ),
    'filter' => array(
      'field' => 'uid',
      'name table' => 'users',
      'name field' => 'name',
      'handler' => 'views_handler_filter_vote_only_user_uid',
    ),
  );
  $data['node']['uid_commented'] = array(
    'title' => t('User commented'),
    'help' => t('Display nodes only if a user commented on the node.'),
    'argument' => array(
      'field' => 'uid',
      'name table' => 'users',
      'name field' => 'name',
      'handler' => 'views_handler_argument_idea_comment_only_user_uid',
    ),
    'filter' => array(
      'field' => 'uid',
      'name table' => 'users',
      'name field' => 'name',
      'handler' => 'views_handler_filter_idea_comment_only_user_uid',
    ),
  );
}

/**
 * Implements hook_quicktabs_alter()
 * Add counter to quicktab title.
 */
function ideal_main_quicktabs_alter(&$quicktabs) { 
  $quicktabs_to_alter = array("all_ideas", "ideas_by_category", "in_action");
  if (in_array($quicktabs->machine_name, $quicktabs_to_alter)) {
    foreach ($quicktabs->tabs as $key => $tab){
      
      // find what quicktab instance we're in, and what block this is
      $block = substr($tab['bid'], strpos($tab['bid'], "block"));
      $view = substr($tab['bid'], 0, strpos($tab['bid'], "block")-1);
      $view = substr($view, strpos($view, "delta")+6);
     
      // if this is one of the tabs we want to add the counter to
      if ($view == "ideas_in_action" || ($block == "block_3" && ($view == "ideas_by_category" || $view == "ideas_all"))) {
        $count = ideal_main_quicktabs_view_counter($view, $block);
        $quicktabs->tabs[$key]['title'] .= " (" . $count . ")";
      }
    }
  }
}

/**
 * Helper function for loading a view and getting the row count.
 */
function ideal_main_quicktabs_view_counter($tab_view, $tab_display, $term=0) {
  $view = views_get_view($tab_view);
  $view->set_display($tab_display);
  if ($term != 0) {
    $view->args[0] = $term;
  }
  else {
    $view->args[0] = arg(1);
  }
  $view->pre_execute();
  $view->execute();
  $count = $view->total_rows ? $view->total_rows : 0;
  return $count;
}
