<?php
/**
 * Implements hook_analytics_dashboard()
 */
function ideal_analytics_analytics_dashboard() {
  $period = _get_time_from_url();
  $from = isset($period[0]) ? $period[0] : strtotime('-1 month');
  $to   = isset($period[1]) ? $period[1] : time();
  $header = $nodes = $comments = $votes = $users = array();
  //==================================
  // Chart for Nodes created per day.
  //==================================
  $i = 0;
  $f = $from;
  while ($f <= $to) {
    // Building the header - list of date from today backward.
    $header[$i]   = date('d.m.y', $f);
    // The number of nodes created each day.
    $nodes[$i] = db_query("SELECT COUNT(*) FROM {node} WHERE type = :type AND FROM_UNIXTIME(created,'%d.%m.%y') = :dete", array(':dete' => $header[$i], ':type' => 'idea'))->fetchField();

    $i ++;
    $f = strtotime("+1 day", $f);
  }
  // Building the rows, array of the data point arrays.
  $rows = array($nodes);
  // The labels for the rows.
  $columns = array('No. Of Ideas');

  // Put all the data into the settings array, 
  // which will be send to draw.

  // Must empty the array first.
  $settings = array();
  $settings['chart']['chartIdeas'] = array(  
    'header' => $header,
    'rows' => $rows,
    'columns' => $columns,
    'chartType' => 'LineChart',// LineChart, PieChart, ,ColumnChart, ,AreaChart, Gauge, BarChart, etc....
    'weight' => -10,  
    'options' => array( // Optionals.
      'curveType' => "function",
      'forceIFrame' => FALSE,  
      'title' => 'Ideas created per day',
      'width' => 500,
      'height' => 300  
    )   
  );

  //Draw it.
  $ret[] = draw_chart($settings);
  
  //==================================
  // Chart for Nodes by category.
  //==================================
  $voc = taxonomy_vocabulary_machine_name_load('categories');
  $tree = taxonomy_get_tree($voc->vid);
  $header = array();
  foreach ($tree as $term) {
    $header[] = $term->name;
    $query = db_select('taxonomy_index', 'ti');
    $query->condition('ti.tid', $term->tid, '=')
          ->fields('ti', array('nid'));
    $terms[] = $query->countQuery()->execute()->fetchField();
    
  }
  $columns = array('Ideas by Category');
  $rows = array($terms);
  
  $settings = array();
  $settings['chart']['chartCategory'] = array(  
    'header' => $header,
    'rows' => $rows,
    'columns' => $columns,
    'chartType' => 'PieChart',
    'weight' => 2,   
    'options' => array( 
      'curveType' => "function", 
      'is3D' => TRUE,  
      'forceIFrame' => FALSE,
      'title' => 'Ideas by category',
      'width' => 500,
      'height' => 300  
    )   
  );
  
  $ret[] = draw_chart($settings); 
  
  //=====================================
  // Chart for projects in progress.
  //=====================================
  $nodes = $header = array();
  $in_action = field_info_field('field_in_action');
  foreach ($in_action['settings']['allowed_values'] as $k => $value) {
    $header[] = $value;
    // The number of nodes created each day.
    $nodes[] = db_query("SELECT COUNT(*) FROM {field_data_field_in_action} WHERE field_in_action_value = :value", array(':value' => $k))->fetchField();
  }
  
  $columns = array('Projects in progress');
  $rows = array($nodes);
  
  $settings = array();
  $settings['chart']['chartProgress'] = array(  
    'header' => $header,
    'rows' => $rows,
    'columns' => $columns,
    'weight' => 3, 
    'chartType' => 'PieChart',// LineChart, PieChart, ,ColumnChart, ,AreaChart, Gauge, BarChart, etc....
    'options' => array( // Optionals.
      'curveType' => "function", 
      'is3D' => TRUE,  
      'forceIFrame' => FALSE, 
      'title' => 'Projects in Progress',
      'width' => 500,
      'height' => 300  
    )   
  );
  
  //Draw it.
  $ret[] = draw_chart($settings);  
  
  //=========================================
  // Chart for blast ideas per day.
  //=========================================
  $header = $nodes = array();
  $fid = db_query("SELECT fid FROM {flags} WHERE name = :name", array(':name' => 'blast_idea'))->fetchField();
  $i = 0;
  $f = $from;
  while ($f <= $to) {
    // Building the header - list of date from today backward.
    $header[$i]   = date('d.m.y', $f);
    // The number of nodes become blast ideas each day.
    $nodes[$i]  = db_query("SELECT COUNT(*) FROM {flag_content} WHERE fid = :fid AND FROM_UNIXTIME(timestamp,'%d.%m.%y') = :dete", array(':fid' => $fid, ':dete' => $header[$i]))->fetchField();
    
    $i ++;
    $f = strtotime("+1 day", $f);
  }
  // Building the rows, array of the data point arrays.
  $rows = array($nodes);
  // The labels for the rows.
  $columns = array('No. Of blast Ideas');
  
  // Put all the data into the settings array, 
  // which will be send to draw.
 
  // Must empty the array first.
  $settings = array();
  $settings['chart']['chartBlast'] = array(  
    'header' => $header,
    'rows' => $rows,
    'columns' => $columns,
    'weight' => 4,   
    'chartType' => 'LineChart',// LineChart, PieChart, ,ColumnChart, ,AreaChart, Gauge, BarChart, etc....
    'options' => array( // Optionals.
      'curveType' => "function",
      'colors' => array('red'), 
      'forceIFrame' => FALSE,  
      'title' => 'Blast Ideas',
      'width' => 500,
      'height' => 300  
    )   
  );
  
  //Draw it.
  $ret[] = draw_chart($settings);
  
  return $ret;
}