<?php
/**
 * Implements hook_init(). 
 */
function google_chart_tools_init() {
  drupal_add_js('https://www.google.com/jsapi', 'external');  
}
/**
 * Draw the chart
 */
function draw_chart($settings) {
  drupal_alter('draw_chart', $settings);
  foreach ($settings['chart'] as $id => $chart) {
    if (!isset($settings['chart'][$id]['containerId'])) {
      $settings['chart'][$id]['containerId'] = strtolower(str_replace(" ", "-", $id));
    }   
  } 
  drupal_add_js(drupal_get_path('module', 'google_chart_tools') . '/google_chart_tools.js');
  drupal_add_js($settings, array('type' => 'setting'));
  $ret = array(
    'title' =>  $chart['options']['title'],
    'id' =>  $id,
    'weight' => isset($chart['weight']) ? $chart['weight'] : 0,
    'markup' =>  "<div id='{$settings['chart'][$id]['containerId']}'></div>"
  );
  return $ret;
}
