<?php

/**
 * Override or insert variables into the node template.
 */
function ideal_comments_preprocess_node(&$vars) {
  // This is stupid, but it's working.
  // We switch between those arrary, to print the comment form on top of the comments list.
  // @todo: there must be a better way doing it.
  $comments = $vars['content']['comments']['comments'];
  $comment_form = $vars['content']['comments']['comment_form'];

  $vars['content']['comments']['comments'] = $comment_form;
  $vars['content']['comments']['comment_form'] = $comments;
}

/**
 * Override or insert variables into the comment template.
 */
function ideal_comments_preprocess_comment(&$vars) {
  $node = $vars['node'];
  $comment = $vars['comment'];
  // Creating a unique comment form for each reply.
  // See ideal_comments_forms(), for handleing those unique forms.
  $comment_form = drupal_get_form("comment_node_{$node->type}_form_{$node->nid}{$comment->cid}", (object) array('pid' => $comment->cid, 'nid' => $node->nid));
  
  $vars['content']['comment_form'] = $comment_form;
  $vars['content']['comment_form']['#weight'] = 1000;
}

/**
 * Implements hook_forms().
 */
function ideal_comments_forms($form_id, $args) {
  $forms = array();
  if (strpos($form_id, 'comment_node_idea_form_') === 0) {
    $forms[$form_id]['callback'] = 'comment_form';
  }
  return $forms;
}