<?php
/**
 * Implements hook_menu().
 */
function ideal_challenge_menu() {
  $items = array();
  $items['admin/config/user-interface/openideal/ideal-challenge'] = array(
    'title' => 'Default Challenge',
    'access arguments' => array('access content'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ideal_challenge_default_challenge_form'),
    'file' => 'ideal_challenge.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Implements hook_theme()
 */
function ideal_challenge_theme($existing, $type, $theme, $path) {
  return array(
    'ideal_challenge_add_idea' => array(
      'variables' => array(),
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function ideal_challenge_block_info() {
  $blocks = array();
  $blocks['challenge_add_idea'] = array(
    'info' => t('ideal challenge add idea'),
  );
  $blocks['challenge_data'] = array(
		'info' => t('Challenge Data Block'),
	);
  $blocks['challenge_add_idea_button'] = array(
    'info' => t('Challenge add idea button'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ideal_challenge_block_view($delta) {
  switch ($delta) {
    case 'challenge_add_idea':
      $block = array(
        'subject' => t('The Challenge'),
        'content' => theme('ideal_challenge_add_idea'),
      );
      break;
    case 'challenge_data':
      $block = array(
        'subject' => t('Time left'),
        'content' => _ideal_challenge_progress(),
      );
      break;
    case 'challenge_add_idea_button':
      $block = array(
        'content' => _ideal_challenge_add_idea_button(),
      );
      break;
  }
  return $block;
}

/*
* Implements hook_views_pre_render().
*/
function ideal_challenge_views_pre_render(&$view) {
  //add js for slider arrows if challenge slider
  if($view->name == 'default_challenge'){
    drupal_add_js('(function($) { Drupal.behaviors.challengeslidearrows = { attach: function(context) {$(".carousel-control.left").click(function(e){ e.preventDefault(); var carousel_id = $(this).attr("href"); $(carousel_id).carousel("prev"); }); $(".carousel-control.right").click(function(e){ e.preventDefault(); var carousel_id = $(this).attr("href"); $(carousel_id).carousel("next"); }); if($(".view-default-challenge .carousel-inner .item").length <= 1){ $(".view-default-challenge").find(".carousel-indicators, .carousel-control").hide();  } } } })(jQuery);', 'inline');
  }
}

function theme_ideal_challenge_add_idea() {
  $output = '';
   // Get the nid (for reference) from the default challenge.
  $challenge_nid = variable_get('default_challenge', NULL);

  if (!empty($challenge_nid)) {
    $challenge = views_embed_view('default_challenge', 'block', $challenge_nid);
    $form = drupal_get_form('ideal_challenge_add_idea_form');

    $output .= $challenge;
    $output .= render($form);
  }
  return $output;
}

/**
 * Generate a block containing a node entry form.
 */
function ideal_challenge_add_idea_form() {
  $form = array();

  $form['header'] = array(
    '#markup' => '<h4 class="ideal-challenge-add-idea">' . t('Be bold! Add your idea:') . '</h4>',
  );

  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#description' => '',
    '#default_value' => '',
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );

  $form['body'] = array(
    '#type' => 'textarea',
    '#title' => t('Body'),
    '#description' => '',
    '#default_value' => '',
    '#required' => TRUE
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Share')
  );

  return $form;
}

/**
 * Additional submit handler for the node add form.
 */
function ideal_challenge_add_idea_form_submit($form, &$form_state) {
  global $user;
  global $language;
  $lang = module_exists('local') ? $language : LANGUAGE_NONE;

  // Get the nid (for reference) anf the terms from the default challenge.
  $challenge_nid = variable_get('default_challenge', NULL);
  $challenge = node_load($challenge_nid);
  $obj = entity_metadata_wrapper('node', $challenge);
  $category = $obj->field_category->value();

//  $wrp = entity_property_values_create_entity('node');
//  $wrp->save();

  // Building the idea node fro, the title and body from th form,
  // and the challenge reference and category from the default challenge.
  $node = new stdClass();
  $node->language = $lang;
  $node->uid = $user->uid;
  $node->type = 'idea';
  $node->title = $form_state['values']['title'];
  $node->body[$node->language][]['value'] = $form_state['values']['body'];
  $node->field_category[$node->language][]['tid'] = $category->tid;
  $node->field_challenge_ref[$node->language][]['target_id'] = $challenge_nid;

  // Saving the node,
  node_object_prepare($node);
  $node = node_submit($node);
  node_save($node);

  drupal_set_message('Your idea was saved');
}

/**
 * Calculate progress of challenge.
 */
function _ideal_challenge_progress() {
	$entity = menu_get_object();
	if ($entity) {
		$node = entity_metadata_wrapper('node', $entity);
		$startdate = $node->field_dates->value->value();
		$enddate = $node->field_dates->value2->value();
		$start = new DateTime(date('c'));
		$end = new DateTime(date('c', $enddate));
    // Time difference from now to end date.
		$diffnow = $start->diff($end);
    // Time difference from start date to end date.
		$diff = abs($enddate - $startdate);
    // Time difference from now to start date.
		$diffpassed = abs(time() - $startdate);
		if ($enddate > time()) {
      // Create HTML for time left counter on challenge.
      // Show year and months only if larger than 0.
			$yearshtml = '';
			if ($diffnow->y > 0) {
				$yearshtml = '<div class="col-xs-4" ><span class="badge" ><h2 class="challenge-date-value">' . $diffnow->y . '</h2>&nbsp;<small class="challenge-date-label small">' . format_plural($diffnow->y, 'Year', 'Years') . '</small></span></div>';
			}
			$monthshtml = '';
			if ($diffnow->y > 0 || $diffnow->m > 0) {
				$monthshtml = '<div class="col-xs-4" ><span class="badge" ><h2 class="challenge-date-value">' . $diffnow->m . '</h2>&nbsp;<small class="challenge-date-label">' . format_plural($diffnow->m, 'Month', 'Months') . '</small></span></div>';
			}
			$dayshtml = '<div class="col-xs-4" ><span class="badge" ><h2 class="challenge-date-value">' . $diffnow->d . '</h2>&nbsp;<small class="challenge-date-label">' . format_plural($diffnow->d, 'Day', 'Days') . '</small></span></div>';
			// If the year is not displayed, display hours.
      $hourshtml = '';
			if ($diffnow->y == 0) {
				$hourshtml = '<div class="col-xs-4" ><span class="badge" ><h2 class="challenge-date-value">' . $diffnow->h . '</h2>&nbsp;<small class="challenge-date-label">' . format_plural($diffnow->h, 'Hour', 'Hours') . '</small></span></div>';
			}
      // If the month is not displayed, display minutes.
			$minuteshtml = '';
			if ($diffnow->y == 0 && $diffnow->m == 0) {
				$minuteshtml = '<div class="col-xs-4" ><span class="badge" ><h2 class="challenge-date-value">' . $diffnow->i . '</h2>&nbsp;<small class="challenge-date-label ">' . format_plural($diffnow->s, 'Min', 'Mins') . '</small></span></div>';
			}
      // Calculate percentage of time passed.
			$complete = round(($diffpassed / $diff) * 100);
      // Output progress bar of time passed and time counter.
			// Progressbar removed:
      // <h4>'. t('Challenge is @complete% completed', array('@complete' => $complete)) . '</h4>
      // <div class="progress"><div class="bar" style="width:' . $complete . '%;"></div></div>
			$output = array(
				'#type' => 'markup',
				'#markup' => '
				<div id="challenge-dates" class="row" >' . $yearshtml . $monthshtml . $dayshtml . $hourshtml . $minuteshtml . '</div>
        <div id="challenge-dates-start-end"><strong>' . t('Start') . '</strong>- ' . format_date($startdate, 'custom', 'n.j.Y') . '<strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'. t('End') . '</strong>- ' . format_date($enddate, 'custom', 'n.j.Y') . '</div>
				',
			);
		}
		else {
      // If end date of challenge is in the past, the challenge is completed.
			$output = array(
				'#type' => 'markup',
				'#markup' => '<div class="well">' . t('The challenge is completed.') .'</div>',
			);
		}
		return $output;
	}
}

/**
 * Output a button to add an idea.
 */
function _ideal_challenge_add_idea_button() {
  $node = menu_get_object();
  if ($node) {
    $nid = $node->nid;
    $output = '<div class="challenge-add-idea-button">';
    $output .= l('Add idea', 'node/add/idea', array('attributes' => array('class' => 'btn btn-success'), 'query' => array('field_challenge_ref' => $nid)));
    $output .= '</div>';
		return $output;
	}
}
