<?php

/**
 * @file
 * Russian services that extend Service Links module
 * Collected by PVasili (vasili@pinchuk.biz)
 */

/**
 * Implements hook_service_links()
 */
function russian_services_service_links() {
  $links = array();

  $links['_ru_100zakladok'] = array(
    'link' => 'http://www.100zakladok.ru/save/?bmurl=<encoded-url>&bmtitle=<encoded-title>',
    'name' => '100zakladok',
    'description' => t('Bookmark this post on 100zakladok'),
  );
  $links['_ru_ruspace'] = array(
    'link' => 'http://www.ruspace.ru/index.php?link=bookmark&action=bookmarkNew&bm=1&url=<encoded-url>&title=<encoded-title>',
    'name' => 'Ruspace',
    'description' => t('Bookmark this post on Ruspace'),
  );
  $links['_ru_misterwong'] = array(
    'link' => 'http://www.mister-wong.ru/index.php?action=addurl&bm_url=<encoded-url>&bm_description=<encoded-title>',
    'name' => 'Mister Wong',
    'description' => t('Bookmark this post on Mister Wong'),
    'icon' => 'misterwong.png',
  );
  $links['_ru_memori'] = array(
    'link' => 'http://memori.ru/link/?sm=1&u_data[url]=<encoded-url>&u_data[name]=<encoded-title>',
    'name' => 'Memori',
    'description' => t('Bookmark this post on Memori'),
  );
  $links['_ru_moemesto'] = array(
    'link' => 'http://moemesto.ru/post.php?url=<encoded-url>&title=<encoded-title>',
    'name' => 'Moemesto',
    'description' => t('Bookmark this post on Moemesto.ru'),
  );
  $links['_ru_myscoop'] = array(
    'link' => 'http://myscoop.ru/add/?URL=<encoded-url>&title=<encoded-title>',
    'name' => 'MyScoop',
    'description' => t('Bookmark this post on MyScoop'),
  );
  $links['_ru_vaau'] = array(
    'link' => 'http://www.vaau.ru/submit/?action=step2&url=<encoded-url>',
    'name' => 'Vaau',
    'description' => t('Bookmark this post on Vaau'),
  );
  $links['_ru_yandex'] = array(
    'link' => 'http://zakladki.yandex.ru/newlink.xml?url=<encoded-url>&name=<encoded-title>',
    'name' => 'Yandex',
    'description' => t('Bookmark this post on Yandex'),
  );
  $links['_ru_linkstore'] = array(
    'link' => 'http://www.linkstore.ru/servlet/LinkStore?a=add&url=<encoded-url>&title=<encoded-title>',
    'name' => 'LinkStore',
    'description' => t('Bookmark this post on LinkStore'),
  );
  $links['_ru_bobrdobr'] = array(
    'link' => 'http://bobrdobr.ru/addext.html?url=<encoded-url>&amp;title=<encoded-title>',
    'name' => 'Bobrdobr',
    'description' => t('Bookmark this post on Bobrdobr'),
  );
  $links['_ru_lopas'] = array(
    'link' => 'http://www.lopas.ru/add_story.php?story_url=<encoded-url>',
    'name' => 'Lopas',
    'description' => t('Bookmark this post on Lopas'),
  );
  $links['_ru_communizm'] = array(
    'link' => 'http://communizm.ru/index.php?mode=addstory&title=<encoded-title>&link=<encoded-url>&description=<encoded-teaser>',
    'name' => 'Communizm',
    'description' => t('Bookmark this post on Communizm'),
  );
  $links['_ru_linksiua'] = array(
    'link' => 'http://links.i.ua/mark/?url=<encoded-url>&ename=<encoded-title>',
    'name' => 'Linksiua',
    'description' => t('Bookmark this post on Links.i.ua'),
  );
  $links['_ru_vkontakte'] = array(
    'link' => 'http://vkontakte.ru/share.php?url=<encoded-url>&title=<encoded-title>',
    'name' => 'VKontakte',
    'description' => t('Share this on VKontakte'),
  );

/* news  todo

  $links['_ru_newsland'] = array(
    'link' => 'http://www.newsland.ru/News/Add/',
    'name' => 'Newsland',
    'description' => t('Bookmark this post on Newsland'),
  );

  $links['_ru_news2'] = array(
    'link' => 'http://news2.ru/add_story.php?url=<encoded-url>',
    'name' => 'News2',
    'description' => t('Bookmark this post on News2'),
  );

  $links['_ru_smi2'] = array(
    'link' => 'http://smi2.ru/add',
    'name' => 'Smi2',
    'description' => t('Bookmark this post on Smi2'),
  );
*/
  return $links;
}
