<?php

/**
 * @file
 * Heartbeat defaults module file
 *
 * This file contains default streams and message templates.
 */

/**
 * Implements hook_heartbeat_stream_info().
 */
function heartbeat_defaults_heartbeat_stream_info() {

  $heartbeatstreams = array();

  $heartbeatstream = new HeartbeatStreamConfig;
  $heartbeatstream->disabled = FALSE; /* Edit this to true to make a default heartbeatstream disabled initially */
  $heartbeatstream->api_version = 1;
  $heartbeatstream->class = 'useractivity';
  $heartbeatstream->name = 'User activity';
  $heartbeatstream->module = 'heartbeat_defaults';
  $heartbeatstream->title = 'User activity';
  $heartbeatstream->path = 'streams/useractivity.inc';
  $heartbeatstream->settings = array(
    'messages_denied' => array(),
    'show_message_times' => 1,
    'show_message_times_grouped' => 1,
    'poll_messages' => '0',
    'num_load_max' => '100',
    'grouping_seconds' => '7200',
    'has_block' => 1,
    'block_items_max' => '25',
    'block_show_pager' => '0',
    'page_disabled' => 0,
    'profilePage' => 1,
    'page_items_max' => '50',
    'page_show_pager' => 0,
    'page_pager_ajax' => 0,
  );
  $heartbeatstream->variables = array();
  $heartbeatstreams['useractivity'] = $heartbeatstream;

  $heartbeatstream = new HeartbeatStreamConfig;
  $heartbeatstream->disabled = FALSE; /* Edit this to true to make a default heartbeatstream disabled initially */
  $heartbeatstream->api_version = 1;
  $heartbeatstream->class = 'siteactivity';
  $heartbeatstream->name = 'Site activity';
  $heartbeatstream->module = 'heartbeat_defaults';
  $heartbeatstream->title = 'Site activity';
  $heartbeatstream->path = 'streams/siteactivity.inc';
  $heartbeatstream->settings = array(
    'messages_denied' => array(),
    'show_message_times' => 1,
    'show_message_times_grouped' => 1,
    'poll_messages' => '0',
    'num_load_max' => '100',
    'grouping_seconds' => '7200',
    'has_block' => 1,
    'block_items_max' => '25',
    'block_show_pager' => '0',
    'page_disabled' => 0,
    'profilePage' => 1,
    'page_items_max' => '50',
    'page_show_pager' => 0,
    'page_pager_ajax' => 0,
  );
  $heartbeatstream->variables = array();
  $heartbeatstreams['siteactivity'] = $heartbeatstream;

  $heartbeatstream = new HeartbeatStreamConfig;
  $heartbeatstream->disabled = FALSE; /* Edit this to true to make a default heartbeatstream disabled initially */
  $heartbeatstream->api_version = 1;
  $heartbeatstream->class = 'relationsactivity';
  $heartbeatstream->name = 'User relations activity';
  $heartbeatstream->module = 'heartbeat_defaults';
  $heartbeatstream->title = 'User relations activity';
  $heartbeatstream->path = 'streams/relationsactivity.inc';
  $heartbeatstream->settings = array(
    'messages_denied' => array(),
    'show_message_times' => 1,
    'show_message_times_grouped' => 1,
    'poll_messages' => '0',
    'num_load_max' => '100',
    'grouping_seconds' => '7200',
    'has_block' => 1,
    'block_items_max' => '25',
    'block_show_pager' => '0',
    'page_disabled' => 0,
    'profilePage' => 1,
    'page_items_max' => '50',
    'page_show_pager' => 0,
    'page_pager_ajax' => 0,
  );
  $heartbeatstream->variables = array();
  $heartbeatstreams['relationsactivity'] = $heartbeatstream;

  return $heartbeatstreams;

}

/**
 * Implements hook_ctools_plugin_api().
 */
function heartbeat_defaults_ctools_plugin_api($owner, $api) {
  if (($owner == 'heartbeat' && $api == 'heartbeat') || ($owner == 'ds' && $api == 'ds') || ($owner == 'ds_extras' && $api == 'ds_extras')) {
    return array('version' => 1);
  }
}

/**
 * Implementation of hook_heartbeat_template_info()
 */
function heartbeat_defaults_heartbeat_template_info() {

  $heartbeatmessagetemplates = array();

  if (module_exists('comment')) {
    $heartbeatmessagetemplate = new HeartbeatMessageTemplate;
    $heartbeatmessagetemplate->disabled = FALSE; /* Edit this to true to make a default heartbeatmessagetemplate disabled initially */
    $heartbeatmessagetemplate->api_version = 1;
    $heartbeatmessagetemplate->message_id = 'heartbeat_add_comment';
    $heartbeatmessagetemplate->description = 'user replied on some content';
    $heartbeatmessagetemplate->message = '<span>!username replied on !title:</span><blockquote><div>!comment</div></blockquote>';
    $heartbeatmessagetemplate->message_concat = '%username% replied on !title.';
    $heartbeatmessagetemplate->perms = 4;
    $heartbeatmessagetemplate->group_type = 'summary';
    $heartbeatmessagetemplate->concat_args = array(
      'group_by' => 'node',
      'group_target' => 'username',
      'group_by_target' => 'title',
      'group_num_max' => '5',
      'merge_separator' => ', ',
      'merge_end_separator' => ' and ',
    );
    $heartbeatmessagetemplate->variables = array(
      '!username' => '',
      '!title' => '',
      '!comment' => '',
    );
    $heartbeatmessagetemplate->attachments = array(
      'flagattachment' => array(
        'flags' => array(
          'like' => 'like',
        ),
      ),
      'flag_count_enabled' => array(
        'flags' => 0,
      ),
      'activitycomments' => array(
        'enabled' => 0,
        'activitycomments_node' => 0,
      ),
    );
    $heartbeatmessagetemplates['heartbeat_add_comment'] = $heartbeatmessagetemplate;
  }

  $heartbeatmessagetemplate = new HeartbeatMessageTemplate;
  $heartbeatmessagetemplate->disabled = FALSE; /* Edit this to true to make a default heartbeatmessagetemplate disabled initially */
  $heartbeatmessagetemplate->api_version = 1;
  $heartbeatmessagetemplate->message_id = 'heartbeat_add_node';
  $heartbeatmessagetemplate->description = 'User adds a node, save user activity';
  $heartbeatmessagetemplate->message = '!username has added !node_type !node_title.';
  $heartbeatmessagetemplate->message_concat = '!username has added the following !types: %node_title%.';
  $heartbeatmessagetemplate->perms = 4;
  $heartbeatmessagetemplate->group_type = 'summary';
  $heartbeatmessagetemplate->concat_args = array(
    'group_by' => 'user',
    'group_target' => 'node_title',
    'group_by_target' => 'username',
    'group_num_max' => '4',
    'merge_separator' => ',',
    'merge_end_separator' => 'and',
  );
  $heartbeatmessagetemplate->variables = array(
    '!username' => '',
    '!node_type' => '',
    '!node_title' => '',
    '!types' => '',
  );
  $heartbeatmessagetemplate->attachments = array(
    'flagattachment' => array(
      'flags' => array(
        'like' => 'like',
      ),
    ),
    'flag_count_enabled' => array(
      'flags' => 1,
    ),
    'activitycomments' => array(
      'enabled' => 1,
      'activitycomments_node' => 1,
    ),
  );
  $heartbeatmessagetemplates['heartbeat_add_node'] = $heartbeatmessagetemplate;

  $heartbeatmessagetemplate = new HeartbeatMessageTemplate;
  $heartbeatmessagetemplate->disabled = FALSE; /* Edit this to true to make a default heartbeatmessagetemplate disabled initially */
  $heartbeatmessagetemplate->api_version = 1;
  $heartbeatmessagetemplate->message_id = 'heartbeat_edit_account';
  $heartbeatmessagetemplate->description = 'user changed his/her account';
  $heartbeatmessagetemplate->message = '!username\'s personal account page has been changed.';
  $heartbeatmessagetemplate->message_concat = 'The personal account page of %username% has been changed.';
  $heartbeatmessagetemplate->perms = 4;
  $heartbeatmessagetemplate->group_type = 'summary';
  $heartbeatmessagetemplate->concat_args = array(
    'group_by' => 'node',
    'group_target' => 'username',
    'group_by_target' => '',
    'group_num_max' => '4',
    'merge_separator' => ',',
    'merge_end_separator' => 'and',
  );
  $heartbeatmessagetemplate->variables = array(
    '!username' => '',
  );
  $heartbeatmessagetemplate->attachments = array(
    'flagattachment' => array(
      'flags' => array(
        'like' => 'like',
      ),
    ),
    'flag_count_enabled' => array(
      'flags' => 1,
    ),
    'activitycomments' => array(
      'enabled' => 1,
      'activitycomments_node' => 0,
    ),
  );
  $heartbeatmessagetemplates['heartbeat_edit_account'] = $heartbeatmessagetemplate;

  $heartbeatmessagetemplate = new HeartbeatMessageTemplate;
  $heartbeatmessagetemplate->disabled = FALSE; /* Edit this to true to make a default heartbeatmessagetemplate disabled initially */
  $heartbeatmessagetemplate->api_version = 1;
  $heartbeatmessagetemplate->message_id = 'heartbeat_edit_node';
  $heartbeatmessagetemplate->description = 'When editing a node, log the users activity';
  $heartbeatmessagetemplate->message = '!username has updated !node_type "!node_title".';
  $heartbeatmessagetemplate->message_concat = '!username has updated %node_title%.';
  $heartbeatmessagetemplate->perms = 4;
  $heartbeatmessagetemplate->group_type = 'summary';
  $heartbeatmessagetemplate->concat_args = array(
    'group_by' => 'user',
    'group_target' => 'node_title',
    'group_by_target' => 'username',
    'group_num_max' => '4',
    'merge_separator' => ',',
    'merge_end_separator' => 'and',
  );
  $heartbeatmessagetemplate->variables = array(
    '!username' => '',
    '!node_type' => '',
    '!node_title' => '',
  );
  $heartbeatmessagetemplate->attachments = array(
    'flagattachment' => array(
      'flags' => array(
        'like' => 'like',
      ),
    ),
    'flag_count_enabled' => array(
      'flags' => 1,
    ),
    'activitycomments' => array(
      'enabled' => 0,
      'activitycomments_node' => 0,
    ),
  );
  $heartbeatmessagetemplates['heartbeat_edit_node'] = $heartbeatmessagetemplate;

  if (module_exists('flag_friend') || module_exists('user_relationships')) {
    $heartbeatmessagetemplate = new HeartbeatMessageTemplate;
    $heartbeatmessagetemplate->disabled = FALSE; /* Edit this to true to make a default heartbeatmessagetemplate disabled initially */
    $heartbeatmessagetemplate->api_version = 1;
    $heartbeatmessagetemplate->message_id = 'heartbeat_become_friends';
    $heartbeatmessagetemplate->description = 'When a user becomes friends with another user (UR)';
    $heartbeatmessagetemplate->message = '!username is now friends with !user2.';
    $heartbeatmessagetemplate->message_concat = '!username is now friends with %user2%.';
    $heartbeatmessagetemplate->perms = 4;
    $heartbeatmessagetemplate->group_type = 'summary';
    $heartbeatmessagetemplate->concat_args = array(
      'group_by' => 'user-user',
      'group_target' => 'user2',
      'group_by_target' => 'username',
      'group_num_max' => '4',
      'merge_separator' => ', ',
      'merge_end_separator' => ' and ',
    );
    $heartbeatmessagetemplate->variables = array(
      '!username' => '',
      '!user2' => '',
    );
    $heartbeatmessagetemplate->attachments = array(
      'activitycomments' => array(
        'enabled' => 1,
        'activitycomments_node' => 0,
      ),
      'flagattachment' => array(
        'flags' => array(
          'like' => 'like',
        ),
        'flag_count_enabled' => array(
          'flags' => 1,
        ),
      ),
    );
    $heartbeatmessagetemplates['heartbeat_become_friends'] = $heartbeatmessagetemplate;
  }

  return $heartbeatmessagetemplates;

}

/**
 * Implements hook_ds_layout_settings_info().
 */
function heartbeat_defaults_ds_layout_settings_info() {

  $dslayouts = array();

  $ds_layout = new stdClass;
  $ds_layout->api_version = 1;
  $ds_layout->id = 'heartbeat_activity|heartbeat_add_comment|default';
  $ds_layout->entity_type = 'heartbeat_activity';
  $ds_layout->bundle = 'heartbeat_add_comment';
  $ds_layout->view_mode = 'default';
  $ds_layout->layout = 'heartbeat_2col';
  $ds_layout->settings = array(
    'hide_empty_regions' => 0,
    'regions' => array(
      'heartbeat_left' => array(
        0 => 'avatar',
      ),
      'heartbeat_content' => array(
        0 => 'message',
      ),
      'heartbeat_footer' => array(
        0 => 'time',
        1 => 'buttons',
        2 => 'attachments',
      ),
    ),
    'fields' => array(
      'avatar' => 'heartbeat_left',
      'message' => 'heartbeat_content',
      'time' => 'heartbeat_footer',
      'buttons' => 'heartbeat_footer',
      'attachments' => 'heartbeat_footer',
    ),
    'classes' => array(),
  );
  $ds_layouts['heartbeat_activity|heartbeat_add_comment|default'] = $ds_layout;

  $ds_layout = new stdClass;
  $ds_layout->api_version = 1;
  $ds_layout->id = 'heartbeat_activity|heartbeat_add_node|default';
  $ds_layout->entity_type = 'heartbeat_activity';
  $ds_layout->bundle = 'heartbeat_add_node';
  $ds_layout->view_mode = 'default';
  $ds_layout->layout = 'heartbeat_2col';
  $ds_layout->settings = array(
    'hide_empty_regions' => 0,
    'regions' => array(
      'heartbeat_left' => array(
        0 => 'avatar',
      ),
      'heartbeat_content' => array(
        0 => 'message',
      ),
      'heartbeat_footer' => array(
        0 => 'time',
        1 => 'buttons',
        2 => 'attachments',
      ),
    ),
    'fields' => array(
      'avatar' => 'heartbeat_left',
      'message' => 'heartbeat_content',
      'time' => 'heartbeat_footer',
      'buttons' => 'heartbeat_footer',
      'attachments' => 'heartbeat_footer',
    ),
    'classes' => array(),
  );
  $ds_layouts['heartbeat_activity|heartbeat_add_node|default'] = $ds_layout;

  $ds_layout = new stdClass;
  $ds_layout->api_version = 1;
  $ds_layout->id = 'heartbeat_activity|heartbeat_edit_account|default';
  $ds_layout->entity_type = 'heartbeat_activity';
  $ds_layout->bundle = 'heartbeat_edit_account';
  $ds_layout->view_mode = 'default';
  $ds_layout->layout = 'heartbeat_2col';
  $ds_layout->settings = array(
    'hide_empty_regions' => 0,
    'regions' => array(
      'heartbeat_left' => array(
        0 => 'avatar',
      ),
      'heartbeat_content' => array(
        0 => 'message',
      ),
      'heartbeat_footer' => array(
        0 => 'time',
        1 => 'buttons',
        2 => 'attachments',
      ),
    ),
    'fields' => array(
      'avatar' => 'heartbeat_left',
      'message' => 'heartbeat_content',
      'time' => 'heartbeat_footer',
      'buttons' => 'heartbeat_footer',
      'attachments' => 'heartbeat_footer',
    ),
    'classes' => array(),
  );
  $ds_layouts['heartbeat_activity|heartbeat_edit_account|default'] = $ds_layout;

  $ds_layout = new stdClass;
  $ds_layout->api_version = 1;
  $ds_layout->id = 'heartbeat_activity|heartbeat_edit_node|default';
  $ds_layout->entity_type = 'heartbeat_activity';
  $ds_layout->bundle = 'heartbeat_edit_node';
  $ds_layout->view_mode = 'default';
  $ds_layout->layout = 'heartbeat_2col';
  $ds_layout->settings = array(
    'hide_empty_regions' => 0,
    'regions' => array(
      'heartbeat_left' => array(
        0 => 'avatar',
      ),
      'heartbeat_content' => array(
        0 => 'message',
      ),
      'heartbeat_footer' => array(
        0 => 'time',
        1 => 'buttons',
        2 => 'attachments',
      ),
    ),
    'fields' => array(
      'avatar' => 'heartbeat_left',
      'message' => 'heartbeat_content',
      'time' => 'heartbeat_footer',
      'buttons' => 'heartbeat_footer',
      'attachments' => 'heartbeat_footer',
    ),
    'classes' => array(),
  );
  $ds_layouts['heartbeat_activity|heartbeat_edit_node|default'] = $ds_layout;

  return $ds_layouts;

}

/**
 * Implements hook_heartbeat_related_uids().
 */
function heartbeat_defaults_heartbeat_related_uids($uid) {

  $uids = array();

  if (module_exists('flag_friend')) {
    foreach (flag_friend_get_friends($uid) as $account) {
      $uids[$account->uid] = $account->uid;
    }
  }

  if (module_exists('user_relationships')) {
    $result = user_relationships_load(array('user' => $uid, 'approved' => 1));
    foreach ($result as $account) {
      $uids[$account->requestee_id] = $account->requestee_id;
    }
  }

  return $uids;

}